//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//


package ua.silentium.entity.vouchers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contact_manager complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact_manager">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="order_email" type="{http://silentium.ua/entity/vouchers}Email"/>
 *         &lt;element name="order_tel_num" type="{http://silentium.ua/entity/vouchers}Tel_num"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact_manager", propOrder = {

})
public class ContactManager {

    @XmlElement(name = "voucher_email", required = true)
    protected String voucherEmail;
    @XmlElement(name = "voucher_tel_num", required = true)
    protected String voucherTelNum;

    /**
     * Gets the value of the orderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherEmail() {
        return voucherEmail;
    }

    /**
     * Sets the value of the orderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherEmail(String value) {
        this.voucherEmail = value;
    }

    /**
     * Gets the value of the orderTelNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherTelNum() {
        return voucherTelNum;
    }

    /**
     * Sets the value of the orderTelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherTelNum(String value) {
        this.voucherTelNum = value;
    }
    @Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Contact Manager(managerEmail=");
		builder.append(voucherEmail);
		builder.append(", managerTelNum=");
		builder.append(voucherTelNum);
		return builder.toString();
}

}
