//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://silentium.ua/entity/vouchers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.silentium.entity.vouchers;
