//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//


package ua.silentium.entity.vouchers;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type_transport.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Type_transport">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bus"/>
 *     &lt;enumeration value="Airpale"/>
 *     &lt;enumeration value="Cruise ship"/>
 *     &lt;enumeration value="Foot"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Type_transport")
@XmlEnum
public enum TypeTransport {

    @XmlEnumValue("Bus")
    BUS("Bus"),
    @XmlEnumValue("Airpale")
    AIRPALE("Airpale"),
    @XmlEnumValue("Cruise ship")
    CRUISE_SHIP("Cruise ship"),
    @XmlEnumValue("Foot")
    FOOT("Foot");
    private final String value;

    TypeTransport(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeTransport fromValue(String v) {
        for (TypeTransport c: TypeTransport.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
