//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//


package ua.silentium.entity.vouchers;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ua.silentium.entity.Entity;


/**
 * <p>Java class for Voucher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Voucher">
 *   &lt;complexContent>
 *     &lt;extension base="{http://silentium.ua/entity}Entity">
 *       &lt;sequence>
 *         &lt;element name="voucher_count" type="{http://silentium.ua/entity/vouchers}Voucher_count"/>
 *         &lt;element name="amount" type="{http://silentium.ua/entity/vouchers}Amount"/>
 *         &lt;element name="Person" type="{http://silentium.ua/entity/vouchers}Person"/>
 *         &lt;element name="Order" type="{http://silentium.ua/entity/vouchers}Order"/>
 *         &lt;element name="voucher_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="date_updated_voucher" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="status_voucher" type="{http://silentium.ua/entity/vouchers}Status_voucher"/>
 *         &lt;element name="voucher_contact" type="{http://silentium.ua/entity/vouchers}Contact_manager"/>
 *       &lt;/sequence>
 *       &lt;attribute name="executed" type="{http://silentium.ua/entity/vouchers}Priority" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Voucher", propOrder = {
    "voucherCount",
    "amount",
    "person",
    "order",
    "voucherDate",
    "dateUpdatedVoucher",
    "statusVoucher",
    "voucherContact"
})
public class Voucher
    extends Entity
{

    @XmlElement(name = "voucher_count")
    protected int voucherCount;
    @XmlElement(required = true)
    protected BigDecimal amount;
    @XmlElement(name = "Person", required = true)
    protected Person person;
    @XmlElement(name = "Order", required = true)
    protected Order order;
    @XmlElement(name = "voucher_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar voucherDate;
    @XmlElement(name = "date_updated_voucher", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateUpdatedVoucher;
    @XmlElement(name = "status_voucher", required = true)
    @XmlSchemaType(name = "string")
    protected StatusVoucher statusVoucher;
    @XmlElement(name = "voucher_contact", required = true)
    protected ContactManager voucherContact;
    @XmlAttribute(name = "priority")
    protected Priority priority;

    /**
     * Gets the value of the voucherCount property.
     * 
     */
    public int getVoucherCount() {
        return voucherCount;
    }

    /**
     * Sets the value of the voucherCount property.
     * 
     */
    public void setVoucherCount(int value) {
        this.voucherCount = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the voucherDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVoucherDate() {
        return voucherDate;
    }

    /**
     * Sets the value of the voucherDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVoucherDate(XMLGregorianCalendar value) {
        this.voucherDate = value;
    }

    /**
     * Gets the value of the dateUpdatedVoucher property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateUpdatedVoucher() {
        return dateUpdatedVoucher;
    }

    /**
     * Sets the value of the dateUpdatedVoucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateUpdatedVoucher(XMLGregorianCalendar value) {
        this.dateUpdatedVoucher = value;
    }

    /**
     * Gets the value of the statusVoucher property.
     * 
     * @return
     *     possible object is
     *     {@link StatusVoucher }
     *     
     */
    public StatusVoucher getStatusVoucher() {
        return statusVoucher;
    }

    /**
     * Sets the value of the statusVoucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusVoucher }
     *     
     */
    public void setStatusVoucher(StatusVoucher value) {
        this.statusVoucher = value;
    }

    /**
     * Gets the value of the voucherContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactManager }
     *     
     */
    public ContactManager getVoucherContact() {
        return voucherContact;
    }

    /**
     * Sets the value of the voucherContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactManager }
     *     
     */
    public void setVoucherContact(ContactManager value) {
        this.voucherContact = value;
    }

    /**
     * Gets the value of the executed property.
     * 
     * @return
     *     possible object is
     *     {@link Priority }
     *     
     */
    public Priority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the executed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Priority }
     *     
     */
    public void setPriority(Priority value) {
        this.priority = value;
    }
    
    
    @Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("\n\tVoucher(id=");
		builder.append(id);
   		builder.append(", priority=");
   		builder.append(priority);
		builder.append(", count=");
		builder.append(voucherCount);
		builder.append(", amount=");
		builder.append(amount);
		builder.append(", \n\t\tPerson:");
		builder.append(person);
		builder.append(", \n\t\tOrder:");
		builder.append(order);
		builder.append(", \n\tvoucherDate=");
		builder.append(voucherDate);
		builder.append(", dateUpdatedVoucher=");
		builder.append(dateUpdatedVoucher);
		builder.append(", ContactManager=");
		builder.append(voucherContact);
		builder.append(", \n\tStatus_voucher=");
		builder.append(statusVoucher);
		builder.append(")\n");
		return builder.toString();
	}

}
